### ISSUE TITLE
Erro na documentação no Diagrama de Sequência - Solicitar Bilhete

### ISSUE THREAD

**Issue by VitorHenriqueOC** [FelipeOka/Source-Code-Inspection#19]
A sequência deveria mostrar que, após a solicitação do bilhete, o sistema deveria verificar e debitar o saldo do usuário antes de realizar a impressão do bilhete. Portanto, o fluxo correto seria: 

1. O usuário faz a solicitação do bilhete
2. O sistema verifica se o saldo disponível é suficiente para cobrir o valor
3. Se houver saldo suficiente, o valor do bilhete é descontado
4. Em seguida, o sistema faz a impressão do bilhete
5. Por fim, o saldo do usuário é atualizado para refletir o novo valor disponível

Esse ordenamento garante que o saldo seja debitado antes da impressão, evitando problemas de inconsistência nas transações.

![Aspose Words 97c57c73-78f7-452a-b23f-493e8740f0af 005](https://github.com/user-attachments/assets/c76b314e-343d-43e2-9569-1501a0e6bafa)

**Comment by FelipeOka** [comment]
Resolvido na Wiki
